<%text>
"""Generated by Alembic - customize as needed."""
</%text>

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

from alembic import op
import sqlmodel.sql.sqltypes  # noqa: F401
import sqlalchemy as sa  # noqa: F401


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
